name: app_skin_music_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0 # Atualize para a versão mais recente
  http: ^1.2.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Atualize para a versão mais recente

flutter:
  uses-material-design: true
